import CheckAuth from '@/middleware/checkAuth';
import MainShell from '@/ui/app/mainShell';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CheckAuth>
      <MainShell>{children} </MainShell>
    </CheckAuth>
  );
}
